In [1]:
import numpy as np

In [10]:
indec = np.arange(200)
np.random.shuffle(indec) 
for i in range(0, 200, 10):
    print(indec[i:i + 10])

[ 28 108 163  25 113 137 117  69 116  48]
[185 171  16 199 150  78 146  47 131  60]
[ 74  82 196 119 126  87  73  33  50 160]
[122 144  80 105 118 152  64  76  10  96]
[ 46 125  49 187  93  90  56 159 155  92]
[103 173 132 179   8 177 167 170  13 133]
[ 81 120  99  32 141  42 191 115  84  19]
[ 86 107 176 147  63  39 180 123  11 162]
[  1  67  17  97  43  41  61 138 111 140]
[124  55   2 165  20 164  70 161  31 193]
[106  27 112 100  23 192  45 190 197 195]
[134  83 139 143  75  71  89 172  26 110]
[182 198   3 145  40   5   7  38  36 158]
[109 168  77 153  21   6 101  12 136 130]
[102 154  54 174   0  91 156 183  53  29]
[135  57  14  51  15 104   9 121  22 128]
[129 194 114  79 149 178 142  66 184 181]
[ 37 151  59  18  24  30 186  85  94  34]
[148   4  95 127 166 175  88 188  35  98]
[ 44 157  62  65  52  72  68 189  58 169]
